30 Ejercicios de SQL: Consolidación de Fundamentos e Intermedios
Base de Datos: formula1.db (SQLite)
Herramienta: Python con SQLAlchemy y Pandas.
Instrucciones: Para cada ejercicio, escribe la consulta SQL necesaria para responder la pregunta y luego el código Python para ejecutarla y mostrar el resultado en un DataFrame de Pandas.

Nivel 1: Fundamentos (SELECT, FROM, WHERE, ORDER BY, LIMIT, DISTINCT)
Ejercicios de calentamiento para asegurar la comprensión de lo básico.

Listado Básico de Pilotos:

Pregunta: ¿Cuáles son los nombres y apellidos (forename, surname) de los primeros 10 pilotos registrados en la base de datos?
Circuitos en un País Específico:

Pregunta: ¿Cuáles son los nombres (name) y ubicaciones (location) de todos los circuitos que se encuentran en 'USA'?
Carreras en un Año Determinado:

Pregunta: ¿Cuáles son los nombres (name) de todas las carreras que se celebraron en el año 2023? (Si no hay en 2023, usa el año más reciente con datos, por ejemplo, 2022 o 2021).
Conteo Total de Constructores:

Pregunta: ¿Cuántos constructores diferentes hay registrados en la tabla constructors?
Temporadas Ordenadas (Descendente):

Pregunta: ¿Cuáles son los años (year) de todas las temporadas, ordenadas desde la más reciente hasta la más antigua? Muestra solo los primeros 5 años.
Pilotos Nacidos Después de una Fecha:

Pregunta: ¿Cuáles son los nombres (forename, surname) de los pilotos nacidos después del 1 de enero de 1995? Ordena por fecha de nacimiento ascendente.
Nacionalidades Únicas de Constructores:

Pregunta: ¿Cuáles son todas las nacionalidades únicas (nationality) de los constructores presentes en la base de datos?
Resultados con Puntos Específicos:

Pregunta: ¿Cuáles son los raceId, driverId y points para los resultados donde se obtuvieron exactamente 6 o 8 puntos? Muestra los primeros 10.
Fechas de Nacimiento Nulas:

Pregunta: ¿Hay algún piloto en la base de datos cuya fecha de nacimiento (dob) sea desconocida (es decir, NULL)? Si los hay, muestra sus driverRef y nombres.
Carreras con Nombres Similares:

Pregunta: ¿Cuáles son los nombres (name) de las carreras que incluyen la palabra "Grand" en su nombre? Muestra los primeros 5.
Nivel 2: Agregación y Agrupamiento (COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING)
Ejercicios que requieren resumir y agrupar datos.

Puntos Totales por Piloto (Top 5):

Pregunta: ¿Cuál es la suma total de puntos (points) acumulados por cada piloto a lo largo de su carrera?
Muestra el driverId y la suma de puntos, ordenado de mayor a menor, para los 5 pilotos con más puntos. (Solo considera points > 0).
Número de Carreras por Año:

Pregunta: ¿Cuántas carreras se celebraron en cada año?
Muestra el año y el conteo de carreras, ordenado por año ascendente.
Promedio de Puntos por Constructor:

Pregunta: ¿Cuál es el promedio de puntos obtenidos por carrera para cada constructor que haya participado en la tabla constructor_results?
Muestra el constructorId y el promedio de puntos, ordenado de mayor a menor.
El Circuito Más Largo y el Más Corto:

Pregunta: ¿Cuál es la longitud (alt) del circuito con la mayor altitud y del circuito con la menor altitud?
Muestra solo los valores mínimo y máximo de alt.
Nacionalidades de Pilotos con Más de 10 Miembros:

Pregunta: ¿Cuáles son las nacionalidades de los pilotos que tienen 10 o más representantes en la base de datos?
Muestra la nacionalidad y el conteo de pilotos, ordenado de mayor a menor conteo.
Años con Menos de 15 Carreras:

Pregunta: ¿Cuáles son los años en los que se celebraron menos de 15 carreras?
Muestra el año y el número de carreras, ordenado por año.
Diferencia entre Mayor y Menor Puntuación en una Carrera:

Pregunta: ¿Cuál es la diferencia entre los puntos máximos y mínimos obtenidos en la carrera con raceId = 1?
Pilotos con una Cantidad Específica de Victorias (Posición 1):

Pregunta: ¿Cuáles driverId han logrado exactamente 5 victorias (position = 1) en sus carreras?
Muestra el driverId y el conteo de victorias.
Promedio de Puntos por Piloto en Carreras con Puntos:

Pregunta: ¿Cuál es el promedio de puntos por carrera para cada piloto, considerando solo las carreras donde obtuvieron puntos (points > 0)?
Muestra el driverId y el promedio, ordenado por promedio descendente.
Conteo de Resultados por Status (Solo Finalizados):

Pregunta: ¿Cuántos resultados tienen un statusId de 1 (que corresponde a 'Finished')?
Nivel 3: Uniones de Tablas (JOINs)
Ejercicios que combinan información de múltiples tablas.

Nombres de Carreras y Circuitos en 2022:

Pregunta: ¿Cuáles son los nombres de las carreras y los nombres de los circuitos donde se llevaron a cabo esas carreras en el año 2022?
Muestra el nombre de la carrera y el nombre del circuito.
Pilotos y sus Equipos en la Temporada 2021:

Pregunta: ¿Cuáles son los nombres completos de los pilotos y los nombres de los constructores (constructors.name) para los que corrieron en el año 2021?
Muestra el nombre del piloto y el nombre del constructor.
Victorias de Ferrari en 2020:

Pregunta: ¿Cuáles fueron las carreras (nombre de la carrera) en las que el constructor 'Ferrari' ganó (posición 1) en el año 2020?
Muestra el nombre de la carrera.
Circuitos que No Han Albergado Carreras desde 2020:

Pregunta: ¿Cuáles son los nombres (name) de los circuitos que no han sido utilizados para ninguna carrera desde el año 2020 (inclusive)?
Muestra el nombre del circuito y su ubicación. (Pista: LEFT JOIN y IS NULL o una subconsulta con NOT IN).
Pilotos con Múltiples Nacionalidades (Si Fuera el Caso - Ejercicio Concepto):

Pregunta: Si hubiera pilotos con la misma combinación de nombre y apellido, pero diferente nacionalidad (ej. por errores de datos), ¿cómo los identificarías?
(Pista: No esperes resultados reales con esta base de datos, es para practicar el GROUP BY en columnas unidas). ¿Cuántas nacionalidades distintas hay por cada forename + surname (nombre completo)?
Puntos Acumulados por Piloto y Constructor en una Carrera Específica:

Pregunta: Para la carrera con raceId = 1000 (o elige una existente, por ejemplo, raceId = 1052 para el Gran Premio de Arabia Saudita 2021), ¿cuántos puntos ganó cada piloto y para qué constructor?
Muestra el nombre del piloto, el nombre del constructor y los puntos obtenidos, ordenado por puntos descendente.
Carreras con 'Weather' en el Nombre del Circuito:

Pregunta: ¿Cuáles son los nombres de las carreras que se celebraron en circuitos cuyo nombre incluye la palabra "Weather"? (No hay un circuito "Weather", busca uno que tenga una 'e' y 'a' en el nombre o usa 'International' para un ejemplo más realista).
Muestra el nombre de la carrera y el nombre del circuito.
Estado Final de Resultados y Su Conteo Global:

Pregunta: ¿Cuántos resultados hay para cada estado final de carrera (status.status)?
Muestra el nombre del estado y el conteo de resultados, ordenado por el conteo descendente.
Pilotos y Sus Puntos Acumulados por Año:

Pregunta: ¿Cuántos puntos acumuló cada piloto en cada año de carrera?
Muestra el nombre del piloto, el año y la suma de puntos, ordenado por nombre de piloto y luego por año. (Pista: GROUP BY piloto y año).
Circuitos con Más de 30 Carreras Históricas:

Pregunta: ¿Cuáles son los nombres de los circuitos que han albergado más de 30 carreras en toda la historia de la Fórmula 1 registrada en la base de datos?
Muestra el nombre del circuito y el conteo de carreras, ordenado por conteo descendente.

In [2]:
import pandas as pd 
from sqlalchemy import create_engine
engine = create_engine("sqlite:///formula1.sqlite")

In [3]:
#pregunta: ¿Cuáles son los nombres y apellidos (forename, surname) de los primeros 10 pilotos registrados en la base de datos?

query = """ select forename, surname
            from drivers
            limit 10"""
df = pd.read_sql_query(query,engine)

In [11]:
df

    forename     surname
0      Lewis    Hamilton
1       Nick    Heidfeld
2       Nico     Rosberg
3   Fernando      Alonso
4     Heikki  Kovalainen
5     Kazuki    Nakajima
6  Sébastien    Bourdais
7       Kimi   Räikkönen
8     Robert      Kubica
9       Timo       Glock

In [12]:
# ¿Cuáles son los nombres (name) y ubicaciones (location) de todos los circuitos que se encuentran en 'USA'?

query = """ select name, location
            from circuits 
            where country = 'USA' """
df = pd.read_sql_query(query,engine)

In [13]:
df

                               name        location
0       Indianapolis Motor Speedway    Indianapolis
1            Phoenix street circuit         Phoenix
2            Detroit Street Circuit         Detroit
3                         Fair Park          Dallas
4                        Long Beach      California
5          Las Vegas Street Circuit          Nevada
6                      Watkins Glen  New York State
7   Riverside International Raceway      California
8     Sebring International Raceway         Florida
9           Circuit of the Americas          Austin
10    Miami International Autodrome           Miami

In [14]:
#Cuáles son los nombres (name) de todas las carreras que se celebraron en el año 2023? (Si no hay en 2023, usa el año más reciente con datos, por ejemplo, 2022 o 2021).

query = """ select name 
            from races
            where year = '2023'"""
df = pd.read_sql_query(query,engine)

In [15]:
df

                        name
0         Bahrain Grand Prix
1   Saudi Arabian Grand Prix
2      Australian Grand Prix
3      Azerbaijan Grand Prix
4           Miami Grand Prix
5          Monaco Grand Prix
6         Spanish Grand Prix
7        Canadian Grand Prix
8        Austrian Grand Prix
9         British Grand Prix
10      Hungarian Grand Prix
11        Belgian Grand Prix
12          Dutch Grand Prix
13        Italian Grand Prix
14      Singapore Grand Prix
15       Japanese Grand Prix
16          Qatar Grand Prix
17  United States Grand Prix
18    Mexico City Grand Prix
19      São Paulo Grand Prix
20      Las Vegas Grand Prix
21      Abu Dhabi Grand Prix

In [ ]:
# Pregunta: ¿Cuántos constructores diferentes hay registrados en la tabla constructors?
query = """select count(distinct contructor)
           from constructors"""

df = pd.read_sql_query(query,engine)

In [17]:
df

                        name
0         Bahrain Grand Prix
1   Saudi Arabian Grand Prix
2      Australian Grand Prix
3      Azerbaijan Grand Prix
4           Miami Grand Prix
5          Monaco Grand Prix
6         Spanish Grand Prix
7        Canadian Grand Prix
8        Austrian Grand Prix
9         British Grand Prix
10      Hungarian Grand Prix
11        Belgian Grand Prix
12          Dutch Grand Prix
13        Italian Grand Prix
14      Singapore Grand Prix
15       Japanese Grand Prix
16          Qatar Grand Prix
17  United States Grand Prix
18    Mexico City Grand Prix
19      São Paulo Grand Prix
20      Las Vegas Grand Prix
21      Abu Dhabi Grand Prix

In [19]:
#¿Cuáles son los años (year) de todas las temporadas, ordenadas desde la más reciente hasta la más antigua? Muestra solo los primeros 5 años.

query = """SELECT year 
           FROM seasons 
           ORDER BY year DESC 
           LIMIT 5;
"""
df = pd.read_sql_query(query,engine)

In [20]:
df

   year
0  2024
1  2023
2  2022
3  2021
4  2020

In [29]:
#Cuáles son los nombres (forename, surname) de los pilotos nacidos después del 1 de enero de 1995? Ordena por fecha de nacimiento ascendente.

query = """ select forename, surname
            from drivers
            where dob > '1/1/1995'
            order by dob asc"""
df = pd.read_sql_query(query, engine)

In [30]:
df

     forename    surname
0    Philippe  Étancelin
1       Luigi    Fagioli
2    Clemente  Biondetti
3      Arthur      Legat
4       Louis     Chiron
..        ...        ...
856     Oscar    Piastri
857      Liam     Lawson
858      Jack     Doohan
859    Franco  Colapinto
860    Oliver    Bearman

[861 rows x 2 columns]

In [32]:
#¿Cuáles son todas las nacionalidades únicas (nationality) de los constructores presentes en la base de datos?
query = """ select count (distinct nationality)
            from constructors"""
df = pd.read_sql_query(query, engine)

In [33]:
df

   count (distinct nationality)
0                            24

In [4]:
#¿Cuáles son los raceId, driverId y points para los resultados donde se obtuvieron exactamente 6 o 8 puntos? Muestra los primeros 10.

query = """select raceId, driverId, points
           from results
           where points = 6 or points = 8
           limit 10
"""
df = pd.read_sql_query(query,engine)

In [5]:
df

   raceId  driverId  points
0      18         2     8.0
1      18         3     6.0
2      19         9     8.0
3      19         5     6.0
4      20         8     8.0
5      20         9     6.0
6      21        13     8.0
7      21         1     6.0
8      22         1     8.0
9      22         8     6.0

In [20]:
#¿Hay algún piloto en la base de datos cuya fecha de nacimiento (dob) sea desconocida (es decir, NULL)? Si los hay, muestra sus driverRef y nombres.

query = """select driverRef 
           from drivers
           where dob = '%null%'
           """
df = pd.read_sql_query(query, engine)

In [21]:
df

Empty DataFrame
Columns: [driverRef]
Index: []

In [18]:
#¿Cuáles son los nombres (name) de las carreras que incluyen la palabra "Grand" en su nombre? Muestra los primeros 5.
query = """select name
           from races
           where name like '%Grand%'
           limit 5
"""
df = pd.read_sql_query(query, engine)

In [19]:
df

                    name
0  Australian Grand Prix
1   Malaysian Grand Prix
2     Chinese Grand Prix
3     Bahrain Grand Prix
4     Spanish Grand Prix

Pregunta: ¿Cuántas carreras se celebraron en cada año?


Pregunta: ¿Cuál es el promedio de puntos obtenidos por carrera para cada constructor que haya participado en la tabla constructor_results?
Muestra el constructorId y el promedio de puntos, ordenado de mayor a menor.
El Circuito Más Largo y el Más Corto:

Pregunta: ¿Cuál es la longitud (alt) del circuito con la mayor altitud y del circuito con la menor altitud?
Muestra solo los valores mínimo y máximo de alt.
Nacionalidades de Pilotos con Más de 10 Miembros:

Pregunta: ¿Cuáles son las nacionalidades de los pilotos que tienen 10 o más representantes en la base de datos?
Muestra la nacionalidad y el conteo de pilotos, ordenado de mayor a menor conteo.
Años con Menos de 15 Carreras:

Pregunta: ¿Cuáles son los años en los que se celebraron menos de 15 carreras?
Muestra el año y el número de carreras, ordenado por año.
Diferencia entre Mayor y Menor Puntuación en una Carrera:

Pregunta: ¿Cuál es la diferencia entre los puntos máximos y mínimos obtenidos en la carrera con raceId = 1?
Pilotos con una Cantidad Específica de Victorias (Posición 1):

Pregunta: ¿Cuáles driverId han logrado exactamente 5 victorias (position = 1) en sus carreras?
Muestra el driverId y el conteo de victorias.
Promedio de Puntos por Piloto en Carreras con Puntos:

Pregunta: ¿Cuál es el promedio de puntos por carrera para cada piloto, considerando solo las carreras donde obtuvieron puntos (points > 0)?
Muestra el driverId y el promedio, ordenado por promedio descendente.
Conteo de Resultados por Status (Solo Finalizados):

In [ ]:
#¿Cuántas carreras se celebraron en cada año? Muestra el año y el conteo de carreras, ordenado por año ascendente. repasar porque no la pude hacer solo
query = """SELECT STRFTIME('%Y', date) AS year, COUNT(*) AS race_count
FROM races
GROUP BY year
ORDER BY year ASC;
"""
df = pd.read_sql_query(query, engine)

In [38]:
df

    year  race_count
0   1950           7
1   1951           8
2   1952           8
3   1953           9
4   1954           9
..   ...         ...
70  2020          17
71  2021          22
72  2022          22
73  2023          22
74  2024          24

[75 rows x 2 columns]

seguir con el nivel 2 con ravi , hay coasas que no se hacer o no me acuerdo como promedio, sacar longitud, etc